### ISSUE TITLE
Don't Include File Extension Conversion for Current File

### ISSUE THREAD

**Issue by jonahisadev** [dawnlabs/alchemy#11]
When a single image is placed in the application, and the "Convert" tab is selected, there is still an option in the dropdown menu to convert the file to the type it already is. For example, I could drag in "Image.jpg" and the dropdown would still have "JPG" as an option to convert it to.

I'd be happy to look into adding this as a feature, as it isn't really a big deal, and I'm sure there are other, more important things you guys are working on.

**Comment by jakedex** [comment]
Can confirm the issue exists, we'd appreciate any help you can offer! On a related note, I think we also want to disallow operations on PDFs for the time being. For example, any merging operation involving a PDF (single PDF, PDF + image, PDF + PDF) isn't supported but is still 'allowed' in the UI.

**Comment by jonahisadev** [comment]
@jakedex I'll see what I can do with that as well. I'm currently having some trouble getting all of the dependencies working correctly, but with enough reading/trial and error, I'm sure I'll get it going.
