### ISSUE TITLE
Add quit button to exit app

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/alchemy#15]

**Comment by dideler** [comment]
I'm unable to find the settings menu that was added in #20. Clicking on the app icon from the menu bar opens up a blank "Drag & drop" window. Right clicking on the app icon from the menu bar doesn't do anything.

Could you please post instructions or a screenshot for how to find the settings menu?

Tried with dawnlabs-alchemy v0.2.0 from brew cask, then with Alchemy.app v1.6.6 (according to the version file it's bundled with) downloaded from https://dawnlabs.io/alchemy/ which for me currently points to https://github.com/dawnlabs/alchemy/releases/download/0.2.0/Alchemy-darwin-x64.zip.

**Comment by mfix22** [comment]
We are still working on the next release, and it has been super delayed due to our work on Carbon (carbon.now.sh).

I want to release this soon, however we do not have a date specified yet.

**Comment by dideler** [comment]
Ah ok, sorry didn't realise this was scheduled for a future release! Assumed it had already shipped.
