### ISSUE TITLE
Doesn't support .webp

### ISSUE THREAD

**Issue by dinosw** [dawnlabs/alchemy#29]
I like the ease of use of this program, but sadly it is missing some formats, .webp being one of them.  
I hope that you will consider adding this in the future :)

**Comment by mfix22** [comment]
I am not familiar with `.webp`! Would you being willing to submit a PR? We would be happy to add the format. 

The underlying conversion library can be found here: https://github.com/dawnlabs/photosorcery

**Comment by dinosw** [comment]
I am not a coder myself, so how to implement the format, I do not know.  
`.webp` is the image format which Google has been implementing over the last few years.  
For instance, all images on Google Search are in `.webp`.  
[wepb format](https://www.wikiwand.com/en/WebP)

**Comment by mfix22** [comment]
@briandennis ImageMagick supports this. Should we enable this type if `imagemagick` is installed on a user's system? Or are you able to add this to `photosorcery`?

**Comment by mfix22** [comment]
https://godoc.org/golang.org/x/image/webp
