### ISSUE TITLE
Only errors

### ISSUE THREAD

**Issue by buzink** [dawnlabs/alchemy#30]
Looks stunning but doesn't work at all. After adding three jpegs and clicking convert to pdf I get only command line like errors

**Comment by mfix22** [comment]
Hey @buzink thanks for the issue! Can you post the exact image names here? Maybe we are still having path issues.

**Comment by qnibru** [comment]
Hi !
I have the same problem
It does this : 
![capture d ecran 86](https://user-images.githubusercontent.com/36766244/37256072-27144452-2556-11e8-8bbb-522da073439b.png)
![capture d ecran 87](https://user-images.githubusercontent.com/36766244/37256083-3ba23b72-2556-11e8-86a6-8ca783fc9bfe.png)

**Comment by mfix22** [comment]
This is definitely a duplicate of #31 😄We will try and fix this soon.
