### ISSUE TITLE
save path not encoded

### ISSUE THREAD

**Issue by jsvisa** [dawnlabs/alchemy#31]
Hi, see the error below, after uploaded the source files to alchemy, the merge process failed by file path is invalid 
![image](https://user-images.githubusercontent.com/3627395/35842760-35070f4e-0b3f-11e8-8897-9a967ef17f58.png)

**Comment by mfix22** [comment]
Hey @jsvisa thanks for the issue! Can you paste the file path here (or at least the unencoded characters) and I will make sure we get this fixed.

**Comment by ericadamski** [comment]
@mfix22 is it possible that this is due to an issue with Unicode encoding here https://github.com/dawnlabs/photosorcery?

**Comment by mfix22** [comment]
@ericadamski absolutely! Photosorcery is the CLI we use under the hood to do the conversions. If you have an idea of how to fix it I would happily accept a PR both repos 😄

**Comment by ericadamski** [comment]
@jsvisa what operating system are you using? Also what version of Alchemy are you on?

I am trying to reproduce the bug with the file name `扫描的文件.jpg` and it seems to encode fine.

**Comment by ericadamski** [comment]
After some investigation I can pretty well conclude that the issue is special characters in file names.

My test was to convert this: `Screen\ Shot\ 2018-03-07\ at\ 7.21.37\ AM.webp` which failed where `test.webp` was successful.

The best solution is to strip out all special characters in JS before it is fed to dawnlabs/photosorcery.

**Comment by mfix22** [comment]
@ericadamski I just tried this locally using `Screen\ Shot\ 2018-03-07\ at\ 7.21.37\ AM.png` and `的中文翻譯 | 英漢字典.png`, and both worked. Are you sure that is the file name you used to recreate the bug?

**Comment by ericadamski** [comment]
@mfix22 I was able to get photosocery to break with those paths, but I also could seem to get alchemy to recreate the bug.

I am wondering if it's an OS path issue. I have only tested this on MacOS

**Comment by jsvisa** [comment]
@ericadamski @mfix22 I'm using macOS too, but I'm sorry, I can't reproduce this issue any more after downloading the newest(1.8.7) Alchemy, (sorry, not remember the previous version)

**Comment by ericadamski** [comment]
@jsvisa no worries! Glad it now works for you!
