### ISSUE TITLE
Stuck Converting

### ISSUE THREAD

**Issue by dshepsis** [dawnlabs/alchemy#36]
I attempted three times to convert different image files (JPG and PNG) and each time, after hitting the "Merge" button, the window changed to "Converting" and stayed that way for several minutes before I manually closed the application via the Windows Task Manager.

I'm using Windows 10.

I've deleted the software out of frustration so I can't do any more testing to figure out the cause, but I can provide more information on my system if it would help.

**Comment by ericadamski** [comment]
@dshepsis thank you for taking the time to open an issue here so that we an make Alchemy better for other people!

If it is possible could you send the file names and types you tried to convert?

**Comment by YukariTea** [comment]
Same issue here, Alchemy 0.5.0., tried merging png and jpg files into a pdf, any combination gets stuck on conversion screen.

**Comment by ericadamski** [comment]
Thank you for submitting!

Are you using Windows as well? Do the file names have any special characters in them? Just trying to workout a connection between other bugs 😁

**Comment by YukariTea** [comment]
Filenames are named 001, 002, etc., no special characters. This was tested on Windows.

**Comment by ericadamski** [comment]
@YukariTea thank you!

**Comment by ericadamski** [comment]
To re-create this issue:

1. Select a combination of formats to convert
2. Select __convert__ option

![screen shot 2018-06-26 at 7 02 57 am](https://user-images.githubusercontent.com/6516758/41907509-1b236954-790f-11e8-92c4-a2b9f47f3fd5.png)

**Comment by briandennis** [comment]
@ericadamski was that error generated on Windows?

**Comment by ericadamski** [comment]
@briandennis nope, that was on my Mac.

**Comment by mfix22** [comment]
@briandennis that must have been introduced in the last release when you
changed how `tmp` works.

**Comment by briandennis** [comment]
@mfix22 what do you mean? Can you point me to what you think may be the problem?

**Comment by briandennis** [comment]
@ericadamski could you upload the files that triggered the error?

**Comment by ericadamski** [comment]
![16926704](https://user-images.githubusercontent.com/6516758/41927376-1458c1c4-7940-11e8-9516-bd8e7e263a74.png)
![img_4806](https://user-images.githubusercontent.com/6516758/41927377-146a9796-7940-11e8-8f15-b4df6387bdaa.JPG)
![screen shot 2018-06-25 at 3 41 19 pm](https://user-images.githubusercontent.com/6516758/41927394-1f18f700-7940-11e8-9c39-8eca8f8642a9.png)


here you are @briandennis

**Comment by briandennis** [comment]
I don't think the problem is that you're converting different formats at the same time. Rather, I think it's that some of the files have the same input format as your output format (it's converting `jpg`s to `jpg`). Or at least, that was the only way I was able to repeat the error — converting all of your images worked fine for me so long as the output type wasn't `jpg` or `png` (tested both both a build from source and pulling the current brew cask).

Does that sound like it could be the culprit? 🤔

**Comment by briandennis** [comment]
I'm fine closing this if you guys want to, but we should look into the original issues.

> I attempted three times to convert different image files (JPG and PNG) and each time, after hitting the "Merge" button, the window changed to "Converting" and stayed that way for several minutes before I manually closed the application via the Windows Task Manager.
I'm using Windows 10.

and 

> Same issue here, Alchemy 0.5.0., tried merging png and jpg files into a pdf, any combination gets stuck on conversion screen. Filenames are named 001, 002, etc., no special characters. This was tested on Windows.

both appear to be a distinct from the issue fixed by https://github.com/dawnlabs/alchemy/pull/44

**Comment by ericadamski** [comment]
Agreed @briandennis 

This is out of my scope, I have no access to a Windows machine.

I am totally into helping implement the solution, upon finding the source of the issue :)
