### ISSUE TITLE
Convert fails with differing extensions

### ISSUE THREAD

**Issue by ericadamski** [dawnlabs/alchemy#43]
This issue originates from #36. See for how to reproduce: https://github.com/dawnlabs/alchemy/issues/36#issuecomment-400268376

I believe the issue stems from here

https://github.com/dawnlabs/alchemy/blob/251eaf98402d04b28c06125c91fffba3507c1e71/src/api.js#L29-L44

Where it takes a list of files to convert but assumes they are all the same format.

We can fix it by grouping and converting each set of files separately or we can change photosorery to accept multiple file types. (It seems that handling this inside of node would be easier)

**Comment by briandennis** [comment]
I believe `photosorcery convert` can handle input files of different types. I think the `-type` flag here corresponds to the _output_ type for the files after conversion.

For example, locally I was able to use Alchemy to convert both `jpg` and `png` files to `gif` in one convert operation without error.

**Comment by ericadamski** [comment]
Interesting, I wasn't able to convert two `jpg`s and a `png` to a `png`. 🤔

now my Alchemy (v0.5.0) is stuck here:

![screen shot 2018-06-26 at 10 08 40 am](https://user-images.githubusercontent.com/6516758/41917651-e9b92704-7928-11e8-80d2-2e0aa185baef.png)

**Comment by briandennis** [comment]
See my comment [here](https://github.com/dawnlabs/alchemy/issues/36), but I think the error is triggered by converting to an output format which is the same as some of the input formats. That would explain why my test case was not hitting the problem while yours was.
