### ISSUE TITLE
0.5.1 release broken

### ISSUE THREAD

**Issue by core-code** [dawnlabs/alchemy#45]
hey there,

your 0.5.1 release with URL
https://github.com/dawnlabs/alchemy/releases/download/0.5.1/Alchemy-mac.zip

and checksum
c49f55f17f155a5e7c5241d364a927f0e9375cf51c11bc24238acf0108c9f958

seems to be broken. the ZIP file can't be decompressed.

**Comment by mfix22** [comment]
Hey @core-code I just reuploaded the `0.5.1` binaries. IIRC the day I released that version I was having trouble with the GitHub uploader, and things went a lot smoother today.

**Comment by core-code** [comment]
thanks!

**Comment by core-code** [comment]
i can confirm the new files work
