### ISSUE TITLE
"Download for Windows" button has incorrect link.

### ISSUE THREAD

**Issue by jensenr30** [dawnlabs/alchemy#55]
When I navigate to https://dawnlabs.github.io/alchemy/ and press the "Download for Windows" button, it directs me to the wrong page.  The button is a link to this old page which no longer exists, producing a 404.  https://github.com/dawnlabs/alchemy/releases/download/0.5.1/Alchemy-win32.zip
I believe this link should be updated to this location, as per the ReadMe.md:  https://github.com/dawnlabs/alchemy/releases/latest

**Comment by mfix22** [comment]
@jensenr30 have you downloaded the build at this link? https://github.com/dawnlabs/alchemy/releases/download/0.5.1/Alchemy-win32.zip 🙂We have had a tough time testing on windows thus far, so want to make sure I'm pointing you to a build that works.

**Comment by jensenr30** [comment]
@mfix22 the link you provided is the exact link that I included in my original issue statement.  When I go to that location, I only see the text "Not Found" in some kind of mono-spaced font:
![image](https://user-images.githubusercontent.com/3083835/54062628-10060d80-41bc-11e9-94e3-c12f6f71127c.png)
I am using Mozilla Firefox, perhaps that makes a difference?
![image](https://user-images.githubusercontent.com/3083835/54062638-214f1a00-41bc-11e9-93b7-d14db1c4858c.png)

**Comment by mfix22** [comment]
Sorry, no you are correct. 

Can you download https://github.com/dawnlabs/alchemy/releases/download/0.5.0/Alchemy-win32.zip directly, and if that build does not work can you try and older build: https://github.com/dawnlabs/alchemy/releases/download/0.4.1/Alchemy-win32.zip or 
https://github.com/dawnlabs/alchemy/releases/download/0.4.0/Alchemy-win32.zip

**Comment by jensenr30** [comment]
@mfix22 - All three links worked perfectly!  Thanks.

**Comment by mfix22** [comment]
Closed with https://github.com/dawnlabs/alchemy/commit/176ded8acc22a2014dc395262f8ed6217bf8acd0
