### ISSUE TITLE
No way to stop it

### ISSUE THREAD

**Issue by SeaMac** [dawnlabs/alchemy#71]
This app lacks ANY form of exit or quit. 
Once launched there is no way to stop it, or remove it from the menu bar, short of shutting down your computer.

**Comment by mfix22** [comment]
You can open the app and press <kbd>CMD+Q</kbd> to quit the app.

**Comment by SeaMac** [comment]
Thank you.

**Comment by mfix22** [comment]
@SeaMac no problem!
